version: '3'

services:
  docker-postgres:
    container_name: container-postgres-dev
    image: postgres
    restart: always
    ports: 
      - "5001:5432"
    environment:
        POSTGRES_USER: ${POSTGRES_USER:-adminfrances1720d}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Frances1720@2020d}
        POSTGRES_DB: ${POSTGRES_DB:-francesdev}
    volumes:
      - ./BasedeDatos/1.Schema-Table.sql:/docker-entrypoint-initdb.d/1.Schema-Table.sql
      - ./BasedeDatos/2.Functions-Seguridad.sql:/docker-entrypoint-initdb.d/2.Functions-Seguridad.sql
  docker-jwt:
    container_name: container-jwt-dev
    #image: image-jwt:1.0
    build: .
    restart: always
    ports:
      - "4001:4000"
    depends_on:
      - docker-postgres
  docker-restapi:
    container_name: container-restapi-dev
    #image: image-restapi:1.0
    build: ../restapi-sigv/ .
    restart: always
    ports:
        - "3001:3000"
    depends_on:
        - docker-postgres