\echo ************************  INICIO EJECUCION SCRIPT 1.Schema-Table.sql  ************************
\echo ************************  1. SET VARIABLES DE SCRIPT
\set postgres_user "adminfrances1720T"
\set postgres_db "francesTest"
\set postgres_tz 'America/Lima'
\echo ************************  postgres_user: :postgres_user **************************************
\echo ************************  postgres_db  : :postgres_db ****************************************
\echo ************************  postgres_tz  : :postgres_tz ****************************************

--CREATE DATABASE francesdev;
--USE francesDev;
--CREATE USER adminfrances1720D with password 'Frances1720D@2020'; DESARROLLO PC LOCAL
--CREATE USER adminfrances1720d with password 'Frances1720@2020d'; CREA ROL
--CREACION DE SCHEMAS 

\c :postgres_db
ALTER DATABASE :postgres_db SET TIMEZONE TO :'postgres_tz';

\echo ************************  2. CREACION DE ESQUEMAS ********************************************
CREATE SCHEMA IF NOT EXISTS SIGV_MAESTRO AUTHORIZATION :postgres_user;
CREATE SCHEMA IF NOT EXISTS SIGV_SEGURIDAD AUTHORIZATION :postgres_user;
CREATE SCHEMA IF NOT EXISTS SIGV_PERSONA AUTHORIZATION :postgres_user;
CREATE SCHEMA IF NOT EXISTS SIGV_VENTAS AUTHORIZATION :postgres_user;

\echo ************************  3. CREACION DE TABLAS EN SIGV_MAESTRO  *****************************
CREATE TABLE IF NOT EXISTS SIGV_MAESTRO.OPERACION(
  IDOPERACION SERIAL NOT NULL,
  DESCRIPCION CHARACTER VARYING(300),
  CONSTRAINT OPERACION_PKEY PRIMARY KEY (IDOPERACION)
);
ALTER TABLE SIGV_MAESTRO.OPERACION
  OWNER to :postgres_user;

INSERT INTO SIGV_MAESTRO.OPERACION (DESCRIPCION) VALUES('INICIO DE SESION CORRECTO');
INSERT INTO SIGV_MAESTRO.OPERACION (DESCRIPCION) VALUES('CLAVE INGRESADA INCORRECTA');
INSERT INTO SIGV_MAESTRO.OPERACION (DESCRIPCION) VALUES('INGRESO DE USUARIO ANULADO');

\echo ************************  4. CREACION DE TABLAS EN SIGV_SEGURIDAD ****************************

CREATE TABLE IF NOT EXISTS SIGV_SEGURIDAD.TERMINAL(
  IDTERMINAL SERIAL NOT NULL,
  TERMINAL CHARACTER VARYING(5),
  IDSUCURSAL INTEGER,
  UNIQUEDEVICEID CHARACTER VARYING(20),
  TRACE BIT(1),
  ESTADO CHARACTER VARYING(1),
  CONSTRAINT TERMINAL_PKEY PRIMARY KEY (IDTERMINAL)
);
ALTER TABLE SIGV_SEGURIDAD.TERMINAL
  OWNER to :postgres_user;

INSERT INTO SIGV_SEGURIDAD.TERMINAL (TERMINAL, IDSUCURSAL, UNIQUEDEVICEID, TRACE, ESTADO) VALUES('INIT1',1,'INIT-TERMINAL-PRUEBA',1::BIT,'A');

CREATE TABLE IF NOT EXISTS SIGV_SEGURIDAD.USUARIO(
  IDUSUARIO SERIAL NOT NULL,
  USUARIO CHARACTER VARYING(20),
  CLAVE CHARACTER VARYING(20),
  IDPERFIL INTEGER,
  IDCOLABORADOR INTEGER,
  ESTADO CHARACTER VARYING(1),
  IDSUCURSAL INTEGER,
  ONLINE INTEGER,
  PCKGSMS INTEGER,
  IDUSUARIOALTA INTEGER,
  CANALALTA  CHARACTER VARYING(10),
  FECHAALTA TIMESTAMP WITH TIME ZONE,
  IDUSUARIOMODIFICACION INTEGER,
  CANALMODIFICACION  CHARACTER VARYING(10),
  FECHAMODIFICACION TIMESTAMP WITH TIME ZONE,
  IDUSUARIOBAJA INTEGER,
  CANALBAJA  CHARACTER VARYING(10),
  FECHABAJA TIMESTAMP WITH TIME ZONE,
  CONSTRAINT USUARIO_PKEY PRIMARY KEY (IDUSUARIO)
);
ALTER TABLE SIGV_SEGURIDAD.USUARIO
    OWNER to :postgres_user;

INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('ADMINISTRADOR','ADMIN',1,1,'A',1,0,1,0,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('CORONA','VIRUS',2,2,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('JCARBONEL','JCARBONEL',2,3,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('CJORGE','CJORGE',2,4,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('FCONTRERAS','FCONTRERAS',2,5,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('LFELIX','LFELIX',2,6,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('VCERVANTES','VCERVANTES',2,7,'A',1,1,0,1,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('VFABRIZIO','VFABRIZIO',2,8,'A',1,1,0,1,'QUERY',NOW());

--SELECT * FROM SIGV_SEGURIDAD.USUARIO;
--DROP SCHEMA IF EXISTS SIGV_SEGURIDAD CASCADE;
--DROP TABLE IF EXISTS SIGV_SEGURIDAD.USUARIO;

CREATE TABLE IF NOT EXISTS SIGV_SEGURIDAD.SETTING(
  IDSETTING SERIAL NOT NULL,
  IDEMPRESA INTEGER,
  CODIGO CHARACTER VARYING(10),
  DESCRIPCION CHARACTER VARYING(100),
  MAXLOGEO INTEGER,
  CADUCIDAD INTEGER,
  ALERTACADUCIDAD INTEGER,
  CLAVEUSUARIONUEVO BIT(1),
  RESETINTENTOLOGEO INTERVAL,
  CONSTRAINT SETTING_PKEY PRIMARY KEY (IDSETTING)
);
ALTER TABLE SIGV_SEGURIDAD.SETTING
  OWNER to :postgres_user;
  
INSERT INTO SIGV_SEGURIDAD.SETTING (IDEMPRESA, CODIGO, DESCRIPCION, MAXLOGEO, CADUCIDAD, ALERTACADUCIDAD, CLAVEUSUARIONUEVO,RESETINTENTOLOGEO) VALUES(1,'GLOBAL-001','CONFIGURACION INICIAL',3,30,3,1::BIT,'5 min');

--SELECT * FROM SIGV_SEGURIDAD.SETTING;
--DROP TABLE IF EXISTS SIGV_SEGURIDAD.SETTING;

CREATE TABLE IF NOT EXISTS SIGV_SEGURIDAD.LOG(
  IDLOG SERIAL NOT NULL,
  IDUSUARIOOPERACION INTEGER,
  CANALOPERACION  CHARACTER VARYING(10),
  FECHAOPERACION TIMESTAMP WITH TIME ZONE,
  IDOPERACION INTEGER,
  UNIQUEDEVICEID CHARACTER VARYING(20),
  DESCRIPCION CHARACTER VARYING(250),
  CONSTRAINT LOG_PKEY PRIMARY KEY (IDLOG)
);
ALTER TABLE SIGV_SEGURIDAD.LOG
  OWNER to :postgres_user;

--SELECT * FROM SIGV_SEGURIDAD.LOG;
--DROP TABLE IF EXISTS SIGV_SEGURIDAD.LOG;

\echo ************************  5. CREACION DE TABLAS EN SIGV_PERSONA *****************************

CREATE TABLE IF NOT EXISTS SIGV_PERSONA.COLABORADOR(
  IDCOLABORADOR SERIAL NOT NULL,
  IDSUCURSAL INTEGER,
  APELLIDOPATERNO CHARACTER VARYING(20),
  APELLIDOMATERNO CHARACTER VARYING(20),
  NOMBRES CHARACTER VARYING(20),
  IDTIPODOCUMENTO INTEGER,
  NUMDOCUMENTO CHARACTER VARYING(15),
  RUC CHARACTER VARYING(20),
  FECHANACIMIENTO DATE,
  SEXO CHARACTER VARYING(1),
  ESTADO CHARACTER VARYING(1),
  IDUSUARIOALTA INTEGER,
  CANALALTA  CHARACTER VARYING(10),
  FECHAALTA TIMESTAMP WITH TIME ZONE,
  IDUSUARIOMODIFICACION INTEGER,
  CANALMODIFICACION  CHARACTER VARYING(10),
  FECHAMODIFICACION TIMESTAMP WITH TIME ZONE,
  IDUSUARIOBAJA INTEGER,
  CANALBAJA  CHARACTER VARYING(10),
  FECHABAJA TIMESTAMP WITH TIME ZONE,
  CONSTRAINT COLABORADOR_PKEY PRIMARY KEY (IDCOLABORADOR)
);
ALTER TABLE SIGV_PERSONA.COLABORADOR
    OWNER to :postgres_user;
    
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'LUYO','HERNANDEZ','LUIS',1,'74309370','0','1994-11-20','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CORONA','VIRUS','COVID19',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CARBONEL','VICENTE','JOHAN',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CORDOVA','FERNANDEZ','JORGE',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CONTRERAS','RAMIREZ','FELIPE',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'FELIX','LUYO','LIZETH',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CERVANTES','HUALPARUCA','VICTOR',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'VICENTE','HERNANDEZ','FABRIZIO',1,'74309370','0','2004-07-01','M','A',1,'QUERY',NOW());

--SELECT * FROM SIGV_PERSONA.COLABORADOR;
--DROP SCHEMA IF EXISTS SIGV_PERSONA CASCADE;
--DROP TABLE IF EXISTS SIGV_PERSONA.COLABORADOR;

\echo ************************  5. CREACION DE TABLAS EN SIGV_VENTAS ******************************

CREATE TABLE IF NOT EXISTS SIGV_VENTAS.EMPRESASUCURSAL(
  IDEMPRESASUCURSAL SERIAL NOT NULL,
  IDEMPRESA INTEGER,
  IDSUCURSAL INTEGER,
  CONSTRAINT EMPRESASUCURSAL_PKEY PRIMARY KEY (IDEMPRESASUCURSAL)
);
ALTER TABLE SIGV_VENTAS.EMPRESASUCURSAL
  OWNER to :postgres_user;
  
INSERT INTO SIGV_VENTAS.EMPRESASUCURSAL (IDEMPRESA, IDSUCURSAL) VALUES(1,1);