\echo ************************  INICIO EJECUCION SCRIPT 4.Carga-Inicial.sql  ************************
\set postgres_user "adminfrances1720T"
\set postgres_db "francesTest"

\c :postgres_db
\echo ************************  CARGA DE INVENTARIO   ****************************
\echo ************************  INSERTANDO MEDIDAS... ****************************
INSERT INTO sigv_inventario.medida (descripcion, abreviado) VALUES ('Unidad','Un.');

\echo ************************  INSERTANDO MARCAS...  ****************************
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('San Mateo','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Coca Cola','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Pepsi','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Kola Real','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Inca Kola','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Sporade','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Generade','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Gatorade','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Powerade','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('360','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Volt','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Cifrut','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Kris','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Gloria','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Pulp','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Frugos','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Fruvi','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Cielo','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Loa','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('San Luis','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Donofrio','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Laive','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Sello de Oro','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Manty','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('La Preferida','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Cerdeña','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('San Fernando','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Scott','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Elite','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Paracas','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Noble','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Suave','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Soy Vida','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Ideal','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Fanny','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Winter','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Herby','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Milo','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Kirma','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Nesquik','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Aconcagua','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Nescafe','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Ecco','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Nestle','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Florida','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('3 Ositos','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Quaker','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Santa Catalina','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Rexona','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Protex','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Kolinos','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Doña Vera','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Garza Real','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Ajinomoto','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Sal de Andrews','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Sapolio','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Maggi','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Konzil','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Suavitel','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Zuko','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('La Llama','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Nosotras','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Babysec','A');
INSERT INTO sigv_inventario.marca (descripcion, estado) VALUES ('Sin Marca','A');

\echo ************************  INSERTANDO CATEGORIAS...  ***************************
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Bebidas','A');
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Embutidos','A');
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Bocaditos','A');
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Panes','A');
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Helados','A');
INSERT INTO sigv_inventario.categoria (descripcion, estado) VALUES ('Bodega','A');

\echo ************************  INSERTANDO SUBCATEGORIAS...  ************************
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Gaseosa',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Frugos',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Agua Mineral',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Energizante',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Chocolatada',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Yogurt',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Leche',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Embolsados',2,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Por Peso',2,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Bocaditos',3,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Pan',4,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Embolsados',4,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Embolsados',5,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Papeleria',6,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Atunes',6,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Mantequillas',6,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Bebidas Cítricas',1,'A');
INSERT INTO sigv_inventario.subcategoria (descripcion, idcategoria, estado) VALUES ('Otros Bodega',6,'A');

\echo ************************  INSERTANDO USUARIOS...  ************************
INSERT INTO sigv_seguridad.usuario (usuario, clave, idperfil, idcolaborador, estado, idsucursal, online, pckgsms, idusuarioalta, canalalta, fechaalta) VALUES ('LOCAL', 'LOCAL',1,1,'A',1,0,1,1,'QUERY',now());

\echo ************************  INSERTANDO PRODUCTOS...  ************************
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('AGUA CIELO 1L','B',3,18,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('AGUA CIELO 625 ML','B',3,18,1,0,0,0,1.2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('AGUA CIELO 2.5L','B',3,18,1,0,0,0,3.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KOLA REAL KR 1L','B',1,4,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA 1.5L','B',1,5,1,0,0,0,7.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COCA COLA 1.5L','B',1,2,1,0,0,0,7.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA 3L','B',1,5,1,0,0,0,12,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KRIS 3L','B',17,13,1,0,0,0,6,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PEPSI 3L','B',1,3,1,0,0,0,8.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('AGUA LOA 2.5L','B',3,19,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COCA COLA 600ML','B',1,2,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COCA COLA ZERO 600ML','B',1,2,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA 600ML','B',1,5,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA ZERO 600ML','B',1,5,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COCA COLA 500ML','B',1,2,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COCA COLA ZERO 500ML','B',1,2,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA 500ML','B',1,5,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('INKA KOLA ZERO 500ML','B',1,5,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SPORADE 500 ML','B',4,6,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('POWERADE 600ML','B',4,9,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('GATORADE 500ML','B',4,8,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('GENERADE 500ML','B',4,7,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('GENERADE VIDRIO 475ML','B',4,7,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('VOLT  300','B',4,11,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('360 300ML','B',4,10,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PULP 1L','B',2,15,1,0,0,0,4.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUGOS 1L','B',2,16,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PULP 1.5 L','B',2,15,1,0,0,0,6.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('LOA 625 ML','B',3,19,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SAN LUIS 625 ML','B',3,20,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHOCOLATADA GLORIA 180 ML','B',5,14,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PULP 250ML','B',2,15,1,0,0,0,1.2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUVI 300ML','B',2,17,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUGOS 300 ML','B',2,16,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUVI 1L','B',2,17,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KOLA REAL KR 400ML','B',1,4,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MANTEQUILLA LA PREFERIDA 90G','B',16,25,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CIFRUT 500 ML','B',17,12,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KRIS 450 ML','B',17,13,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PULP CAJITA 315ML','B',2,15,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('BATIMIX GLORIA','B',6,14,1,0,0,0,3.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MANTY','B',16,24,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MANTEQUILLA LIGHT LAIVE','B',16,22,1,0,0,0,8.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SWIS LAIVE','B',16,22,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MANTEQUILLA CON SAL LAIVE 100G','B',16,22,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MANTEQUILLA CON SAL GLORIA 100G','B',16,14,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SELLO DE ORO 45G','B',16,23,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHICHARRON DE PRENSA LA PREFERIDA','B',16,25,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA LA PREFERIDA','B',16,25,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MORTADELA LA PREFERIDA','B',16,25,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('HOT DOG 3 CERDEÑA','B',8,26,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('HOT DOG 6 CERDEÑA','B',8,26,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA CERDEÑA','B',8,26,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('HOT DOG 3 POLLO SAN FERNANDO','B',8,27,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('HOT DOG 6 POLLO SAN FERNANDO','B',8,27,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('HOT DOG 3 PAVITA SAN FERNANDO','B',8,27,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PATÉ 100G SAN FERNANDO','B',8,27,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHORIZO PARRILLERO 1 SAN FERNANDO','B',8,27,1,0,0,0,1.7,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMON SANDWICH 5 TAJADAS SAN FERNANDO','B',8,27,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MORTADELA SAN FERNANDO','B',8,27,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHICHARRON DE PRENSA SAN FERNANDO','B',8,27,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA SAN FERNANDO','B',8,27,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA PAVITA SAN FERNANDO','B',8,27,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMON DEL PAIS SAN FERNANDO 100G','B',9,27,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MORTADELA SAN FERNANDO 100G','B',9,27,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHICHARRON DE PRENSA CERDEÑA 100G','B',9,26,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHICHARRON DE PRENSA SAN FERNANDO 100G','B',9,27,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMON SANDWICH SAN FERNANDO 100G','B',9,27,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA DE POLLO SAN FERNANDO 100G','B',9,27,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CHOCOLATADA GLORIA CAJA 1L','B',5,14,1,0,0,0,5.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('360 LATA','B',4,10,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('DOLCETTO','B',13,21,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SUBLIME','B',13,21,1,0,0,0,3.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('ALASKA','B',13,21,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SIN PARAR CROCANTE DE FRESA','B',13,21,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SIN PARAR CHOCOLATE INTENSO','B',13,21,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRIO RICO','B',13,21,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('BOMBONES','B',13,21,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MINISANDWICH','B',13,21,1,0,0,0,1.2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MEGA','B',13,21,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('SIN PARAR COPA','B',13,21,1,0,0,0,4,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('COPA K-BANA','B',13,21,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('TRIKA','B',13,21,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('TARTALETA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PALITOS 7X1 SOL','B',10,64,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('BUDIN','B',10,64,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('NIDITOS DE AMOR 6X1','B',10,64,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('OREJA','B',10,64,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('EMPANADA DULCE','B',10,64,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('EMPANADITA DULCE 6X1','B',10,64,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('EMPANADA DE CARNE','B',10,64,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('EMPANADA DE POLLO','B',10,64,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('EMPANADA MIXTA','B',10,64,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('MIL HOJAS','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('ROSQUITAS 5X1','B',10,64,1,0,0,0,1,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PIONONO','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('JAMONADA ESPECIAL 100G','B',9,27,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUGOS CITRUS FRESH 625ML','B',17,16,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('FRUGOS FRESH 1.5L','B',17,16,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('YOPIMIX','B',6,22,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('QUESO EDAM LAIVE','B',8,22,1,0,0,0,5.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('QUESO EDAM LAIVE 100G','B',9,22,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('GALLETA DE AGUA','B',12,64,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PAN CAMPESINO','B',12,64,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('BIZCOCHO TORTU ALACRA','B',12,64,1,0,0,0,3,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('ALFAJOR','B',10,64,1,0,0,0,1.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CONO DE MANJAR','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KEKE DE PIÑA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KEKE DE NARANJA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('KEKE DE ZANAHORIA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('TAMAL','B',18,64,1,0,0,0,3.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PIE DE MANZANA','B',10,64,1,0,0,0,2.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('PAÑUELOS','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CREMA VOLTEADA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('LECHE ASADA','B',10,64,1,0,0,0,2,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CAJA LECHE GLORIA LIGHT 1L ROJO','B',7,14,1,0,0,0,4.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CAJA LECHE GLORIA DESLACTOSADA 1L CELESTE','B',7,14,1,0,0,0,5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CAJA LECHE GLORIA 1L AZUL','B',7,14,1,0,0,0,4.5,'','A',2,'WEB');
INSERT INTO sigv_inventario.producto (descripcion, tipo, idsubcategoria, idmarca, idmedida, stock_min, stock_max, costo, pventa, imagen, estado, idusuarioalta, canalalta) VALUES ('CAJA LECHE GLORIA EVAPORADA 1L AMARILLA','B',7,14,1,0,0,0,5,'','A',2,'WEB');

\echo ************************  FIN EJECUCION SCRIPT 4.Carga-Inicial.sql  ************************

\echo ************************  TODO TERMINO BIEN :)  ************************