CREATE DATABASE 

USE

CREATE USER adminfrances1720 with password 'Frances1720@2020';

CREATE SCHEMA IF NOT EXISTS SIGV_SEGURIDAD AUTHORIZATION adminfrances1720; /* CREA ROL Y ASIGNA ESQUEMA */


CREATE TABLE SIGV_SEGURIDAD.USUARIO(
  IDUSUARIO SERIAL NOT NULL,
  USUARIO CHARACTER VARYING(20),
  CLAVE CHARACTER VARYING(20),
  IDPERFIL INTEGER,
  IDCOLABORADOR INTEGER,
  ESTADO CHARACTER VARYING(1),
  IDSUCURSAL INTEGER,
  ONLINE INTEGER,
  PCKG_SMS INTEGER,
  CANALALTA  CHARACTER VARYING(10),
  FECHAALTA TIMESTAMP WITH TIME ZONE,
  IDUSUARIOMODIFICACION INTEGER,
  CANALMODIFICACION  CHARACTER VARYING(10),
  FECHA_MODIFICACION TIMESTAMP WITH TIME ZONE,
  IDUSUARIOBAJA INTEGER,
  CANALBAJA  CHARACTER VARYING(10),
  FECHABAJA TIMESTAMP WITH TIME ZONE,
  CONSTRAINT USUARIO_PKEY PRIMARY KEY (IDUSUARIO)
);

INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKG_SMS, CANALALTA, FECHAALTA) VALUES ('ADMINISTRADOR','ADMIN',1,1,'G',1,0,1,'QUERY',NOW());

INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKG_SMS, CANALALTA, FECHAALTA) VALUES ('JFABRIZIO','JFABRIZIO',2,2,'G',1,1,0,'QUERY',NOW());

SELECT * FROM SIGV_SEGURIDAD.USUARIO;

DROP SCHEMA IF EXISTS SIGV_SEGURIDAD CASCADE;
