/* CREATE DATABASE francesdev;*/

--USE francesDev;

/* CREATE USER adminfrances1720D with password 'Frances1720D@2020'; DESARROLLO PC LOCAL  */
CREATE USER adminfrances1720d with password 'Frances1720@2020d'; /* CREA ROL */

CREATE SCHEMA IF NOT EXISTS SIGV_SEGURIDAD AUTHORIZATION adminfrances1720d; /* ASIGNA ESQUEMA A ROL CREADO */

CREATE TABLE SIGV_SEGURIDAD.USUARIO(
  IDUSUARIO SERIAL NOT NULL,
  USUARIO CHARACTER VARYING(20),
  CLAVE CHARACTER VARYING(20),
  IDPERFIL INTEGER,
  IDCOLABORADOR INTEGER,
  ESTADO CHARACTER VARYING(1),
  IDSUCURSAL INTEGER,
  ONLINE INTEGER,
  PCKGSMS INTEGER,
  IDUSUARIOALTA INTEGER,
  CANALALTA  CHARACTER VARYING(10),
  FECHAALTA TIMESTAMP WITH TIME ZONE,
  IDUSUARIOMODIFICACION INTEGER,
  CANALMODIFICACION  CHARACTER VARYING(10),
  FECHAMODIFICACION TIMESTAMP WITH TIME ZONE,
  IDUSUARIOBAJA INTEGER,
  CANALBAJA  CHARACTER VARYING(10),
  FECHABAJA TIMESTAMP WITH TIME ZONE,
  CONSTRAINT USUARIO_PKEY PRIMARY KEY (IDUSUARIO)
);
ALTER TABLE SIGV_SEGURIDAD.USUARIO
    OWNER to adminfrances1720d;

INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('ADMINISTRADOR','ADMIN',1,1,'G',1,0,1,0,'QUERY',NOW());
INSERT INTO SIGV_SEGURIDAD.USUARIO (USUARIO, CLAVE, IDPERFIL, IDCOLABORADOR, ESTADO, IDSUCURSAL, ONLINE, PCKGSMS, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES ('ANOEMI','ANOEMI',2,2,'G',1,1,0,1,'QUERY',NOW());

/*
SELECT * FROM SIGV_SEGURIDAD.USUARIO;
DROP SCHEMA IF EXISTS SIGV_SEGURIDAD CASCADE;
DROP TABLE IF EXISTS SIGV_SEGURIDAD.USUARIO;
*/
/* SIGV_PERSONA */

CREATE SCHEMA IF NOT EXISTS SIGV_PERSONA AUTHORIZATION adminfrances1720d;

CREATE TABLE SIGV_PERSONA.COLABORADOR(
  IDCOLABORADOR SERIAL NOT NULL,
  IDSUCURSAL INTEGER,
  APELLIDOPATERNO CHARACTER VARYING(20),
  APELLIDOMATERNO CHARACTER VARYING(20),
  NOMBRES CHARACTER VARYING(20),
  IDTIPODOCUMENTO INTEGER,
  NUMDOCUMENTO CHARACTER VARYING(15),
  RUC CHARACTER VARYING(20),
  FECHANACIMIENTO DATE,
  SEXO CHARACTER VARYING(1),
  ESTADO CHARACTER VARYING(1),
  IDUSUARIOALTA INTEGER,
  CANALALTA  CHARACTER VARYING(10),
  FECHAALTA TIMESTAMP WITH TIME ZONE,
  IDUSUARIOMODIFICACION INTEGER,
  CANALMODIFICACION  CHARACTER VARYING(10),
  FECHAMODIFICACION TIMESTAMP WITH TIME ZONE,
  IDUSUARIOBAJA INTEGER,
  CANALBAJA  CHARACTER VARYING(10),
  FECHABAJA TIMESTAMP WITH TIME ZONE,
  CONSTRAINT COLABORADOR_PKEY PRIMARY KEY (IDCOLABORADOR)
);
ALTER TABLE SIGV_PERSONA.COLABORADOR
    OWNER to adminfrances1720d;
    
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'RIOFRIO','MIO','JOSE',1,'74309370','0','1994-11-20','M','G',1,'QUERY',NOW());
INSERT INTO SIGV_PERSONA.COLABORADOR (IDSUCURSAL, APELLIDOPATERNO, APELLIDOMATERNO, NOMBRES, IDTIPODOCUMENTO, NUMDOCUMENTO, RUC, FECHANACIMIENTO, SEXO, ESTADO, IDUSUARIOALTA, CANALALTA, FECHAALTA) VALUES(1,'CORDOVA','FERNANDEZ','ROSMERY',1,'74309370','0','2004-07-01','M','G',1,'QUERY',NOW());

/*
SELECT * FROM SIGV_PERSONA.COLABORADOR;
DROP SCHEMA IF EXISTS SIGV_PERSONA CASCADE;
DROP TABLE IF EXISTS SIGV_PERSONA.COLABORADOR;
*/

